# Generated by Django 4.2.5 on 2023-09-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='preview',
        ),
    ]
