# Generated by Django 4.2.5 on 2023-09-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_remove_course_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview',
            field=models.ImageField(default=1, upload_to='course_previews/', verbose_name='Превью (картинка)'),
            preserve_default=False,
        ),
    ]
