# Generated by Django 4.2.5 on 2023-09-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_alter_course_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, upload_to='lesson_previews/', verbose_name='Превью'),
        ),
    ]
