# Generated by Django 4.2.5 on 2023-10-02 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0013_subscription_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
