# Generated by Django 4.2.5 on 2023-10-02 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0014_alter_subscription_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscribers',
        ),
        migrations.AlterField(
            model_name='course',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
