# Generated by Django 4.2.5 on 2023-10-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0015_remove_subscription_subscribers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
