# Generated by Django 4.2.5 on 2023-10-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0016_course_is_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subscribers',
        ),
    ]
